[package]
name = "rbt-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
datafusion.workspace = true
arrow.workspace = true
tokio.workspace = true
rbt-core.workspace = true
rbt-materializer.workspace = true
rbt-scan.workspace = true
rbt-testing.workspace = true
iceberg.workspace = true
iceberg-datafusion.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true

[dev-dependencies]
tempfile = "3"
