[package]
name = "rbt-materializer"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
iceberg.workspace = true
parquet.workspace = true
arrow.workspace = true
tokio.workspace = true
rbt-core.workspace = true
rbt-testing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde_json = { workspace = true }

[dev-dependencies]
tempfile = "3"
